### ISSUE TITLE
No SLA state breaks loading vApps

### ISSUE THREAD

**Issue by Draper1** [rubrikinc/rubrik-extension-for-vcd#15]
**What happened**:

Objects in a `No SLA` state do not appear in the Datagrid when populating the hash.

**What you expected to happen**:

Objects appear with a `Not Protected` status

**How to reproduce it (as minimally and precisely as possible)**:

Add an object to Rubrik without any previous protection

**Anything else we need to know?**:

**Environment**:
- SDK version: vCD SDK 1.0.0
- Others: Rubrik 4.2.1 and 5.0 tested

**Comment by Draper1** [comment]
Adding SLA check to validate the SLA for this state and will load vApp in with a `Not Protected` state. This will go into release v1.0.1 today.

**Comment by rfitzhugh** [comment]
Any update @Draper1 ? My team will be showcasing the plugin on Thursday as a part of Cloud Field Day.

**Comment by Draper1** [comment]
@rfitzhugh Just running it through some tests now and will confirm it's good; v1.0.0 will work fine as long as you've assigned an SLA to the vApps at least once.

**Comment by Draper1** [comment]
Resolved in release v1.0.1
