### ISSUE TITLE
Start guide

### ISSUE THREAD

**Issue by poltraf** [rubrikinc/rubrik-extension-for-vcd#22]
**What would you like to be added**:
IN case of vCloud Director 9.7, no need to build the Lifecycle plugin, since is already in place
**Why is this needed**:
Modification (or maybe, addition to) the Start Guide

**Comment by poltraf** [comment]
I'm afraid thdere are some libes missing on the NGINX CentOS server configuration, from missing directories to path to cache, and so on. Following those steps, and correcting what causes nginx not starting, the proxy recalls recursively itself causing a "400 Bad Request - Request Header Or Cookie Too Large".

**Comment by Draper1** [comment]
Hi @poltraf!

Thanks for the feedback - let me double check the install guides and confirm where the issues are - I'll push an update in the next few days to fix these. I'll look at including a script to deploy all the necessary configuration in addition to the manual steps.

**Comment by Draper1** [comment]
Documents resolved in latest release, Nginx proxy guide and config all updated to be working.

Details in Gitbook her: https://rubrik.gitbook.io/vcd-extension-for-rubrik/getting-started/quick-start-nginx-reverse-proxy

Closing Issue.
