### ISSUE TITLE
Does the plugin support multiple Rubrik Clusters connecting to a single vCD?

### ISSUE THREAD

**Issue by xucito** [rubrikinc/rubrik-extension-for-vcd#34]
**What would you like to be added**:
Multi-Cluster support

**Why is this needed**:
Multi-site environments

If it does support it, how does the behavior work?

**Comment by Draper1** [comment]
@xucito apologies on the delay here. The plugin leverages the SDK for plugins provided by VMware (https://github.com/vmware/vcd-ext-sdk). The calls in the SDK check for multi-site when they make a request to the vCD API. All the APIs will be made in the user's current context but some functions currently do not deal with adding multisite headers whilst others do. For example: The `Get` function provided by the SDK, directs the API calls straight towards the base URL for vCD:

https://github.com/vmware/vcd-ext-sdk/blob/301c079b82d727f2c12f34a6f12fcf1ce13d8f08/typescript/api-client/projects/vcd/sdk/src/client/vcd.api.client.ts#L234

Is there a specific issue you are seeing with multi-site environments? We can look to change the code to better support multi-sites if required.

**Comment by Draper1** [comment]
Stale Issue. Closing - please re-open if issues still persist.
