### ISSUE TITLE
Credentials Failed Validation, Please Go Back and Check Credentials.

### ISSUE THREAD

**Issue by ilsuky** [rubrikinc/rubrik-extension-for-vcd#37]
**What happened**:
Cannot Validate User Credentials, against our rubrik.
Error: Credentials Failed Validation, Please Go Back and Check Credentials.

**Console Log**
Http failure response for https://rubrik.xxx.com/api/v1/session?organization_id=Organization:::f79a61de-7c79-41bc-9d1f-83fee9a51c91: 0 Unknown Error

"Authenticate" - for Admin User works. See all VMware and vApps.

**How to reproduce it (as minimally and precisely as possible)**:
Try to add / Update Cluster Credentials -> Insert all Information, User Works direct on Rubrik Gui, By checking Credentials on second page.

**Anything else we need to know?**:

I have no Proxy installation, cause iam on 5.2.0-p2-9418 with CloudDirector 10.1.0.15967236, not needed any more.
CORS changed by Quick Start Information

**Environment**:
- Rubrik - 5.2.0
- CloudDirector - 10.1.0
- PluginVersion - 1.1.3

**Comment by pmilano1** [comment]
Greetings Chris -

Thanks for the feedback!

vCD v10.1 support is due out with CDM 5.3, please note that CDM 5.2 supports vCD v10.0.1. 

We will consider this information as we ramp up extension test on CDM 5.3.

Do you have this issue on vCD v10.0.1?

Thanks! 

Pete Milanese
Mgr, FDSE

**Comment by ilsuky** [comment]
Hi Pete,

thanks for your answer.
Yes my vCD is: VMware Cloud Director-Version: 10.1.0.15967236 Fri Apr 03 16:10:39 UTC 2020
But from the Rubrik, i can see all vcdOrgs and vApps.
That works all fine with 5.2.

And from the vCD, i can login to my Rubrik generally, for admin login, to match after Rubrik Org with vCD Org.
But only the Customer User Credential check failed.

**Comment by Draper1** [comment]
Hey @ilsuky 

Just following up on this - 5.2.1 recently went GA which included Cloud Director 10.1 support - in addition, the plugin has been through a few bug fixes and releases which should resolve most these issues highlighted. 

Latest plugin is here: https://github.com/rubrikinc/rubrik-extension-for-vcd/releases/tag/1.1.7

Would you be able to validate the latest plugin and Rubrik versions resolve the issues you were seeing?

**Comment by Draper1** [comment]
Closing. Please re-open if issues still persist.
