### ISSUE TITLE
Enable snapshot retention selection option in vCD plugin 

### ISSUE THREAD

**Issue by DeepakRai94** [rubrikinc/rubrik-extension-for-vcd#42]
**Need to enable snapshot retention selection option in vCD plugin during the selection of unprotecting the vApp **:

**It's selecting default forever snapshot retention option while doing from vCD plugin**:

**Comment by Draper1** [comment]
This is resolved with v1.1.8 - releases updated: https://github.com/rubrikinc/rubrik-extension-for-vcd/releases/tag/1.1.8

Could you please confirm??

**Comment by DeepakRai94** [comment]
it's resloved now
