### ISSUE TITLE
Ability to restore a deleted VM of a deleted vAPP

### ISSUE THREAD

**Issue by odraghi** [rubrikinc/rubrik-extension-for-vcd#44]
**What would you like to be added**:
The ability to restore a deleted VM of a deleted vAPP

**Why is this needed**:
If a tenant user delete a vAPP from vCD he can't restore it with the Plugin.
Can you add a kind of "Snapshot management" view where tenant can see and restore snapshot ?

**Comment by Draper1** [comment]
Resolved in https://github.com/rubrikinc/rubrik-extension-for-vcd/pull/52 - please update to the latest plugin.
