### ISSUE TITLE
Support for VCD 10.2

### ISSUE THREAD

**Issue by wynner** [rubrikinc/rubrik-extension-for-vcd#48]
Hello,
Is there a plan to support VCD 10.2?
Currently it looks like VCD 10.1 is the highest version supported.
Thanks

**Comment by jaapbrasser** [comment]
Hello @wynner,

I'll take a look into this, did you confirm that the extension doesn't work with VCD 10.2 or is it only a documentation issue?

**Comment by wynner** [comment]
Hello @jaapbrasser
No known issue.
Simply a validation request and documentation update. It's holding back a potential upgrade to VCD 10.2 to fix a different issue. That is all. Thank you

**Comment by azizo** [comment]
@jaapbrasser any update on this?

**Comment by pipalm** [comment]
Doesn't seem to work;
Running 
Rubrik 5.31
Cloud Director 10.2.1
Extension 1.1.8

Dasboard works fine, but the protection tab is just blank with 'Gathering vAPPs'
Tried with Externsion 1.1.9 too but when configuring tenant credentials, the rubrik organization cannot be selected

**Comment by ilsuky** [comment]
@jaapbrasser any update on this? Cause we would update to 10.2 soon.

**Comment by Draper1** [comment]
Resolved in https://github.com/rubrikinc/rubrik-extension-for-vcd/pull/52 - please update to the latest plugin.
