### ISSUE TITLE
On protection page, second page doesnot populate  

### ISSUE THREAD

**Issue by sameshdhankhar** [rubrikinc/rubrik-extension-for-vcd#49]
On Protection page where the list of all vAPPs are visible, 1st  page work fine but second page and after it comes out empty with no error. filtering VM still works.

We expected that as i have 100+ VM's the second page must have the list of VM's.

Environment information: 
Rubrik 5.3.
Cloud Director 10.2.2
Extension 1.1.9
<img width="941" alt="rubrik-plugin" src="https://user-images.githubusercontent.com/85218014/120440579-bf7abc00-c394-11eb-9884-578bf754c8cf.PNG">

**Comment by Draper1** [comment]
Resolved in #52 - please update to the latest plugin.
