### ISSUE TITLE
Plugin 1.20 no comunication with VCD 10.3 wrong API version 

### ISSUE THREAD

**Issue by MWIBCS** [rubrikinc/rubrik-extension-for-vcd#51]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:vmext="http://www.vmware.com/vcloud/extension/v1.5" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:common="http://schemas.dmtf.org/wbem/wscim/1/common" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:ovfenv="http://schemas.dmtf.org/ovf/environment/1" xmlns:ns9="http://www.vmware.com/vcloud/versions" message="The request has invalid accept header: Invalid API version requested. 

Supported API versions are: [37.0.0-alpha, 36.1, 36.0, 35.2, 35.0, 34.0, 33.0 [D], 32.0 [D], 31.0 [D]] ([D] indicates deprecated versions)" majorErrorCode="406" minorErrorCode="NOT_ACCEPTABLE"/>

Request URL: 
Request Method: POST
Status Code: 406 Not Acceptable
Remote Address: 8.8.8.8
Referrer Policy: strict-origin-when-cross-origin
Cache-Control: no-store, must-revalidate
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 437
Content-Type: application/vnd.vmware.vcloud.error+xml;version=36.1
Date: Mon, 31 Jan 2022 13:54:08 GMT
Keep-Alive: timeout=15, max=100
Server: Apache
Vary: Accept-Encoding
X-VMWARE-VCLOUD-CEIP-ID: 94a8a3f9-c699-4e7b-9bb3-ca0e1c617c83
X-VMWARE-VCLOUD-REQUEST-EXECUTION-TIME: 3
X-VMWARE-VCLOUD-REQUEST-ID: 3d2fb358-7c5a-426d-ab90-f42c5cce8d54
Accept: application/*+xml;version=30.0
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,de-DE;q=0.8,de;q=0.7
Connection: keep-alive
Content-Length: 516
Content-Type: application/vnd.vmware.vcloud.metadata+xml
Cookie: _pk_ses.1.f2b5=0; vcloud_jwt=eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtd2lhIiwiaXNzIjoiYTkzYzlkYjktNzQ3MS0zMTkyLThkMDktYThmN2VlZGE4NWY5QDBhNDJlZWYzLTQ0ZjItNGFhMC1hMWJjLTcyMDNkMzBlZTVkOCIsImV4cCI6MTY0MzcyMzEyOSwidmVyc2lvbiI6InZjbG91ZF8xLjAiLCJqdGkiOiJjM2UzNDNhYTQzMTU0MjdkODM3MDU3NzY3NTZjODhlNyJ9.G-dr1AsjDuosIaRuyn_1uMlmUv_50kPPGcirKQm2EDo8Fh-X6svEI0_M4wUOJ3zkTKOGDKzOXNNzJlPnUQSX6WbTGUveGwDsKcTh2y4OXO7s3qV2T9NmPey_pKZB2SoW-80sJJawg_oD4XsKZKiTiVsgdRChhkL8LomtXReY5Vg2IZ0rnRz32GO3avEuIyXNEedUt68tFk5hDO41Qh-FpKjTbi0kMXSssrJwc5FXSoh6fAUFSNeg6SwciSQHI3NgXrmzOtSndbN68yJyP4Xjy16JjyFhpj42yN4aTXDEc4WkH7TqioFIUVZr-eAzSu1m_1stdEp9O_haXeuzfsycsQ; vcloud_session_id=c3e343aa4315427d83705776756c88e7; _pk_id.1.f2b5=1190b39af1df086f.1643625453.2.1643637248.1643636404..baaa2b0fa8ac840b7d60159edea8e7f6da55a0cd1e5f8f75ae757868c94f4121
Host:  vcdl.mydomain.com
Origin: https://vcdl.mydomain.com
Referer: https://vcdl.mydomain.com/provider/plugins/UnVicmlr/rubrik/settings
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
x-vcloud-authorization: c3e343aa4315427d83705776756c88e7

**Comment by MWIBCS** [comment]
Version of Inviroment
Rubrik 6.0.2-p1-13329
VCD 10.3.1.18738571

**Comment by Draper1** [comment]
Resolved in PR #52 - please update to the latest plugin.
